### ISSUE TITLE
 Could not import OPL wrappers. Make sure than OPL bin directory is in the PATH

### ISSUE THREAD

**Issue by dormantroot** [IBMDecisionOptimization/doopl-examples#2]
not sure why I'm  getting the following error.

python --version
Python 3.6.8 :: Anaconda, Inc.

echo $PATH
/opt/conda/bin:/opt/conda/condabin:/opt/ibm/ILOG/CPLEX_Studio128/cplex/bin/x86-64_linux:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echo $LD_LIBRARY_PATH
:/opt/ibm/ILOG/CPLEX_Studio128/opl/bin/x86-64_linux:/opt/ibm/ILOG/CPLEX_Studio128/opl/bin/x86-64_linux:/opt/ibm/ILOG/CPLEX_Studio128/opl/bin/x86-64_linux

command/error
~/doopl-examples-master/examples# python3 Convert.py

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/doopl/opl.py", line 8, in <module>
    from doopl.internal.opl1290.opl import *
  File "/opt/conda/lib/python3.6/site-packages/doopl/internal/opl1290/opl.py", line 7, in <module>
    from . import _opl
ImportError: libopl1290.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/doopl/opl.py", line 11, in <module>
    from doopl.internal.opl1280.opl import *
  File "/opt/conda/lib/python3.6/site-packages/doopl/internal/opl1280/opl.py", line 7, in <module>
    from . import _opl
ImportError: /opt/conda/lib/python3.6/site-packages/doopl/internal/opl1280/_opl.so: undefined symbol: PyInstance_Type
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/doopl/opl.py", line 8, in <module>
    from doopl.internal.opl1290.opl import *
  File "/opt/conda/lib/python3.6/site-packages/doopl/internal/opl1290/opl.py", line 7, in <module>
    from . import _opl
ImportError: libopl1290.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/doopl/opl.py", line 11, in <module>
    from doopl.internal.opl1280.opl import *
  File "/opt/conda/lib/python3.6/site-packages/doopl/internal/opl1280/opl.py", line 7, in <module>
    from . import _opl
ImportError: /opt/conda/lib/python3.6/site-packages/doopl/internal/opl1280/_opl.so: undefined symbol: PyInstance_Type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Convert.py", line 10, in <module>
    from doopl.factory import *
  File "/opt/conda/lib/python3.6/site-packages/doopl/factory.py", line 7, in <module>
    from doopl.opl import *
  File "/opt/conda/lib/python3.6/site-packages/doopl/opl.py", line 15, in <module>
    raise ImportError('Could not import OPL wrappers. Make sure than OPL bin directory is in the PATH')
ImportError: Could not import OPL wrappers. Make sure than OPL bin directory is in the PATH

**Comment by vlkong** [comment]
It looks like the link flags don't work with conda's version of python. I' ll dig into this and upload a fix asap. The workaround for the moment is to use a non-anaconda python interpreter.

**Comment by vlkong** [comment]
doopl 12.9.0.15 fixes the issue. Please update and have fun.

**Comment by dormantroot** [comment]
hmm... not sure what I'm doing wrong. I decided to go with regular python 3.6 and still getting same error. I'm listing the details below. Let me know if you need any additional info

```
root@b7fc5c2425f9:/doopl-examples-master/examples# python3 -V
Python 3.6.7
root@b7fc5c2425f9:/doopl-examples-master/examples# pip3 list
certifi (2019.3.9)
chardet (3.0.4)
cplex (12.8.0.1)
docloud (1.0.369)
docplex (2.9.141)
doopl (12.9.0.15)
idna (2.8)
pip (8.1.1)
pycurl (7.43.0)
pygobject (3.20.0)
python-apt (1.1.0b1+ubuntu0.16.4.2)
requests (2.21.0)
setuptools (20.7.0)
six (1.12.0)
unattended-upgrades (0.1)
urllib3 (1.24.2)
wheel (0.29.0)
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@b7fc5c2425f9:/doopl-examples-master/examples# echo $PATH
/opt/ibm/ILOG/CPLEX_Studio128/cplex/bin/x86-64_linux:/opt/ibm/ILOG/CPLEX_Studio128/cplex/bin/x86-64_linux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@b7fc5c2425f9:/doopl-examples-master/examples# echo $LD_LIBRARY_PATH
/opt/ibm/ILOG/CPLEX_Studio128/cplex/bin/x86-64_linux:
root@b7fc5c2425f9:/doopl-examples-master/examples# python3 Convert.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/doopl/opl.py", line 8, in <module>
    from doopl.internal.opl1290.opl import *
  File "/usr/local/lib/python3.6/dist-packages/doopl/internal/opl1290/opl.py", line 7, in <module>
    from . import _opl
ImportError: libopl1290.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/doopl/opl.py", line 11, in <module>
    from doopl.internal.opl1280.opl import *
  File "/usr/local/lib/python3.6/dist-packages/doopl/internal/opl1280/opl.py", line 7, in <module>
    from . import _opl
ImportError: libopl1280.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/doopl/opl.py", line 8, in <module>
    from doopl.internal.opl1290.opl import *
  File "/usr/local/lib/python3.6/dist-packages/doopl/internal/opl1290/opl.py", line 7, in <module>
    from . import _opl
ImportError: libopl1290.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/doopl/opl.py", line 11, in <module>
    from doopl.internal.opl1280.opl import *
  File "/usr/local/lib/python3.6/dist-packages/doopl/internal/opl1280/opl.py", line 7, in <module>
    from . import _opl
ImportError: libopl1280.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Convert.py", line 10, in <module>
    from doopl.factory import *
  File "/usr/local/lib/python3.6/dist-packages/doopl/factory.py", line 7, in <module>
    from doopl.opl import *
  File "/usr/local/lib/python3.6/dist-packages/doopl/opl.py", line 15, in <module>
    raise ImportError('Could not import OPL wrappers. Make sure than OPL bin directory is in the PATH')
ImportError: Could not import OPL wrappers. Make sure than OPL bin directory is in the PATH
root@b7fc5c2425f9:/doopl-examples-master/examples#


```

**Comment by vlkong** [comment]
This time, /opt/ibm/ILOG/CPLEX_Studio128/opl/bin/x86-64_linux seems to be missing from your LD_LIBRARY_PATH (you only have the cplex binaries)

**Comment by dormantroot** [comment]
duh, silly me! Thanks for pointing that out.

**Comment by kbadams3** [comment]
Edit: I think I found the error, I don't have the right version of CPLEX Optimization Studio!

Hi, I am having a similar problem even though I have 

> C:\Program Files\ibm\ILOG\CPLEX_Studio1271\cplex\bin\x64_win64

 in the PATH. I am trying to use doopl 12.9.0.16 with Python 3.6 in PyCharm. Below is the full error:

```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\doopl\opl.py", line 8, in <module>
    from doopl.internal.opl1290.opl import *
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\doopl\internal\opl1290\opl.py", line 7, in <module>
    from . import _opl
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\doopl\opl.py", line 11, in <module>
    from doopl.internal.opl1280.opl import *
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\doopl\internal\opl1280\opl.py", line 7, in <module>
    from . import _opl
ImportError: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\doopl\opl.py", line 8, in <module>
    from doopl.internal.opl1290.opl import *
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\doopl\internal\opl1290\opl.py", line 7, in <module>
    from . import _opl
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\doopl\opl.py", line 11, in <module>
    from doopl.internal.opl1280.opl import *
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\doopl\internal\opl1280\opl.py", line 7, in <module>
    from . import _opl
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/username/PycharmProjects/sched/test.py", line 10, in <module>
    from doopl.factory import *
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\doopl\factory.py", line 7, in <module>
    from doopl.opl import *
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\doopl\opl.py", line 15, in <module>
    raise ImportError('Could not import OPL wrappers. Make sure than OPL bin directory is in the PATH')
ImportError: Could not import OPL wrappers. Make sure than OPL bin directory is in the PATH
```
Any help is appreciated. Thanks.

**Comment by srjkoolen** [comment]
Dear all,

I am struggling with the connection between python and CPLEX. 

Before I show the error, I will explain my end goal. 
I want to handle the data in python, run automatically from python a cplex optimization model (written in cplex) and I want to use the cplex output in python to visualize this. 
I read online that I need the Doopl package which makes this python/cplex connection but i am failing to get it working. I know that it probably has to do with a missing path file, but I can’t get it to work. 
Who can help me. 

I hope to hear from you. 

Kind regards,

Sven
**The file that i am running:** 

import os
import sys

sys.path.append("D:\\Program Files\\IBM\\ILOG\\CPLEX_Studio1263\\opl\\bin\\x64_win64")

from doopl.opl import *

**The error that i am getting:**

Traceback (most recent call last):
  File "C:\AppData\Local\Continuum\anaconda3\envs\lib\site-packages\doopl\opl.py", line 8, in <module>
    from doopl.internal.opl1290.opl import *
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\lib\site-packages\doopl\internal\opl1290\opl.py", line 7, in <module>
    from . import _opl
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\lib\site-packages\doopl\opl.py", line 11, in <module>
    from doopl.internal.opl1280.opl import *
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\lib\site-packages\doopl\internal\opl1280\opl.py", line 7, in <module>
    from . import _opl
ImportError: DLL load failed: The specified module could not be found.
